//nav links
export const hebrewVariables=
{
    homePage:"דף הבית",
    forum:"פורום",
    myCourse:"הקורס שלי",
    classSchedual:'לו"ז כיתות',
    logout:"התנתק",
    syllabus:"סילבוס",
    edit:"עריכה",
    addChanges: "בצע שינויים",
    studentsGrades:"ציוני סטודנטים",
    students:"סטודנטים",
    createCourse:"יצירת קורס",
    staff:"סגל",
    studentsGrade:"ציוני סטודנטים",  
    createStaff:"יצירת משתמש חדש",
    fillDetails:"אנא מלא את הפרטים בבקשה",
    createStuffBtn:"צור משתמש",
    closeBtn:"סגור",
    confirmWindow:"האם אתה בטוח?",
    eventName:"שם האירוע",
    typeHere:"הקלד כאן",
    send:"שלח",
    message:"הודעה",
    update:"עדכן",
    delete:"מחק",
    confirmUpdates:"אישור עדכונים",
    firstName:"שם פרטי",
    lastName:"שם משפחה",
    course:"קורס",
    edit:"ערוך",
    myGrades:"הציונים שלי",
    techCarrer:"טק-קריירה",
    techCarrerDescription1:"מרכז הכשרה טכנולוגי,",
    techCarrerDescription2:"לצעירים יוצאי קהילת אתיופיה בישראל",
    news:"חדשות",
    events:"אירועים",
    contact:"צור קשר",
    techAdress:"בת שבע 3, מתחם טלרד, לוד",
    techPhone:"08-3738000",
    techEmail:"info@tech-career.org",
    connectToAccount:"התחבר לחשבונך",
    email:"אימייל",
    loginAs:"התחבר כ",
    student:"סטודנט",
    addStuff:"הוסף איש צות",
    courses:"קורסים",
    addStudent:"הוספת סטודנט",
    age:"גיל",
    password:"סיסמא",
    add:"הוסף",
    registerd:"נרשם במערכת",
    emailSent:"נשלח מייל עם פרטי התחברות לכתובת",
    fullName:"שם מלא",
    ok:"אישור",
    links:"קישורים",
    presentation:"שיעורים והרצאות",
    phone:"טלפון",
    testName:"שם מבחן",
    grade:"ציון",
    addTest:"הוסף מבחן",
    login:"התחבר לחשבונך",
    courseName:"שם הקורס",
    developer: "פיתוח",
    devNetEngineers:"ניהול רשתות",
    SOCAnalyst: "סייבר",
    createNewSubject:"צור נושא חדש",
    courseType:"סוג קורס",
    currentPassword:"סיסמא נוכחית",
    newPassword:"סיסמא חדשה",
    confirmPassword:"אימות סיסמא",
    updatePassword:"עדכן סיסמא",
    CourseSchedule: "לוז קורס",
    eventsHeadline: "ארועים בטק קריירה",
    eventNamePlaceholder: "שם הארוע",
    eventMessagePlaceholder: "הקלד כאן",
    eventNameTitle: "שם האירוע",
    eventMessageTitle: "הודעה",
    responsibleFor:"אחראי על:",
    job:"תפקיד:",
    homework:"משימות",
    addHomework:"הוסף משימה",
    createHomework:"צור משימה",
    subject:"נושא",
    description:"תיאור",
    createBy: "נוצר על ידי",
    selectGender:"זכר/נקבה:",
    male:"זכר",
    female:"נקבה",
    homePage:"דף בית",

} 
